---
- name: ansible-playbook
  hosts: all
  become: true
  tasks:
    - name: create deployment
      command: kubectl apply -f /home/ubuntu/deployment.yml
    - name: create service
      command: kubectl apply -f /home/ubuntu/service.yml