kind: Service
apiVersion: v1
metadata:
  name: myservice
  labels:
    app: mycontainer
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      NodePort: 31000
      targetPort: 80
  selector:
    labels:
      app: mycontainer